server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment # zipkin 链路追踪相关配置
  zipkin:
    base-url: http://zipkin9411.com:9411
  sleuth:
    sampler:
      # 采样率值，介于0-1之间，1则表示全部采集
      probability: 1

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
      
 